# Generated by Django 3.2.15 on 2022-10-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_profile_calendly_org_page'),
        ('campaign_leads', '0003_auto_20221017_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioRawWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('a', 'POST'), ('b', 'GET')], default='a', max_length=1)),
                ('twilio_webhook_type', models.CharField(choices=[('a', 'Message'), ('b', 'Status')], default='a', max_length=1)),
                ('errors', models.ManyToManyField(blank=True, null=True, to='core.ErrorModel')),
            ],
        ),
        migrations.CreateModel(
            name='TwilioMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('inbound', models.BooleanField(default=True)),
                ('Type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], default='whatsapp', max_length=50)),
                ('Body', models.TextField(blank=True, null=True)),
                ('ProfileName', models.TextField(blank=True, null=True)),
                ('system_user_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('SmsSid', models.CharField(blank=True, max_length=50, null=True)),
                ('MessageSid', models.CharField(blank=True, max_length=50, null=True)),
                ('SmsMessageSid', models.CharField(blank=True, max_length=50, null=True)),
                ('AccountSid', models.CharField(blank=True, max_length=50, null=True)),
                ('ApiVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('WaId', models.CharField(blank=True, max_length=50, null=True)),
                ('NumMedia', models.CharField(blank=True, max_length=3, null=True)),
                ('NumSegments', models.CharField(blank=True, max_length=3, null=True)),
                ('ReferralNumMedia', models.CharField(blank=True, max_length=3, null=True)),
                ('SmsStatus', models.CharField(blank=True, max_length=20, null=True)),
                ('errors', models.ManyToManyField(blank=True, null=True, to='core.ErrorModel')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_leads.campaignlead')),
                ('raw_webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio.twiliorawwebhook')),
            ],
        ),
    ]
