# Generated by Django 3.2.15 on 2022-10-14 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.TextField(blank=True, null=True)),
                ('company_logo_white', models.ImageField(default='default.png', upload_to='company_images')),
                ('company_logo_black', models.ImageField(default='default.png', upload_to='company_images')),
                ('company_logo_trans', models.ImageField(default='default.png', upload_to='company_images')),
                ('campaign_leads_enabled', models.BooleanField(default=False)),
                ('free_taster_enabled', models.BooleanField(default=False)),
                ('active_campaign_enabled', models.BooleanField(default=False)),
                ('active_campaign_url', models.TextField(blank=True, null=True)),
                ('active_campaign_api_key', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('json_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTasterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('guid', models.TextField(blank=True, null=True)),
                ('customer_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_business_phone_number_id', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp_access_token', models.TextField(blank=True, null=True)),
                ('whatsapp_business_account_id', models.TextField(blank=True, null=True)),
                ('company', models.ManyToManyField(to='core.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('avatar', models.ImageField(default='default.png', upload_to='profile_images')),
                ('company', models.ManyToManyField(to='core.Company')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FreeTasterLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.freetasterlink')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='freetasterlink',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site'),
        ),
        migrations.AddField(
            model_name='freetasterlink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
