# Generated by Django 3.2.15 on 2022-10-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='calendly_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='calendly_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='calendly_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='calendly_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='calendly_webhook_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='guid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
