# Generated by Django 3.2.15 on 2022-10-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_auto_20221014_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=30, null=True)),
                ('alias', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.phonenumber_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.RemoveField(
            model_name='site',
            name='whatsapp_business_phone_number_id',
        ),
        migrations.RemoveField(
            model_name='site',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('a', 'Owner'), ('b', 'Manager'), ('c', 'Employee')], default='c', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sites_allowed',
            field=models.ManyToManyField(blank=True, null=True, related_name='profile_sites_allowed', to='core.Site'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.RemoveField(
            model_name='site',
            name='company',
        ),
        migrations.AddField(
            model_name='site',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.CreateModel(
            name='WhatsappNumber',
            fields=[
                ('phonenumber_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.phonenumber')),
                ('whatsapp_business_phone_number_id', models.CharField(blank=True, max_length=50, null=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('code_verification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('verified_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.phonenumber',),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site'),
        ),
        migrations.AddField(
            model_name='site',
            name='default_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_default_number', to='core.whatsappnumber'),
        ),
    ]
