# Generated by Django 3.2.15 on 2022-10-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0004_campaignlead_last_dragged'),
        ('whatsapp', '0004_remove_whatsapptemplate_latest_reason'),
        ('core', '0005_attachederror'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachederror',
            name='campaign_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='campaign_leads.campaignlead'),
        ),
        migrations.AlterField(
            model_name='attachederror',
            name='type',
            field=models.CharField(choices=[('101', 'You can only edit an active template once every 24 hours'), ('201', "Whatsapp Template not found Whatsapp's system"), ('202', "There is no Whatsapp Business linked to this Lead's assosciated Site"), ('203', "There is no 1st Whatsapp Template linked to this Lead's assosciated Site"), ('204', "There is no 2nd Whatsapp Template linked to this Lead's assosciated Site"), ('205', "There is no 3rd Whatsapp Template linked to this Lead's assosciated Site")], default='c', max_length=5),
        ),
        migrations.AlterField(
            model_name='attachederror',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='whatsapp.whatsapptemplate'),
        ),
    ]
