# Generated by Django 3.2.15 on 2022-10-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221020_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachederror',
            name='admin_action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attachederror',
            name='recipient_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachederror',
            name='whatsapp_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='core.whatsappnumber'),
        ),
        migrations.AlterField(
            model_name='attachederror',
            name='type',
            field=models.CharField(choices=[('101', 'You can only edit an active template once every 24 hours'), ('102', 'The system can not send Whatsapp Templates without a template name'), ('103', 'The number of parameters submitted does not match the Whatsapp Template (contact Winser Systems)'), ('201', "Whatsapp Template not found Whatsapp's system"), ('202', "There is no Whatsapp Business linked to this Lead's assosciated Site"), ('203', "There is no 1st Whatsapp Template linked to this Lead's assosciated Site"), ('204', "There is no 2nd Whatsapp Template linked to this Lead's assosciated Site"), ('205', "There is no 3rd Whatsapp Template linked to this Lead's assosciated Site")], default='c', max_length=5),
        ),
    ]
