# Generated by Django 3.2.15 on 2022-10-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_attachederror_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='calendly_org_page',
            new_name='calendly_event_page_url',
        ),
    ]
