# Generated by Django 3.2.15 on 2022-10-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221023_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='calendly_webhook_created',
        ),
        migrations.AddField(
            model_name='attachederror',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='core.site'),
        ),
    ]
