# Generated by Django 3.2.15 on 2022-10-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221026_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachederror',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
