# Generated by Django 3.2.15 on 2022-10-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_attachederror_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachederror',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
