# Generated by Django 3.2.15 on 2022-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221106_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='whatsapp_app_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
