# Generated by Django 3.2.15 on 2022-11-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_attachederror_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='template_sending_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attachederror',
            name='type',
            field=models.CharField(choices=[('0101', 'You can only edit an active template once every 24 hours'), ('0102', 'The system can not send Whatsapp Templates without a template name'), ('0103', 'The number of parameters submitted does not match the Whatsapp Template (contact Winser Systems)'), ('1104', 'Message failed to send because more than 24 hours have passed since the customer last replied to this number. You can still send a template message at 24 hour intervals instead'), ('1105', 'Message failed to send because the Whatsapp account is not yet registered (contact Winser Systems)'), ('1201', "Whatsapp Template not found Whatsapp's system"), ('1202', "There is no Whatsapp Business linked to this Lead's assosciated Site"), ('1203', "There is no 1st Whatsapp Template linked to this Lead's Campaign"), ('1204', "There is no 2nd Whatsapp Template linked to this Lead's Campaign"), ('1205', "There is no 3rd Whatsapp Template linked to this Lead's Campaign"), ('1206', 'This site has template messaging currently disabled, reenable it on the site configuration page')], default='c', max_length=5),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
            ],
        ),
        migrations.AddField(
            model_name='attachederror',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='errors', to='core.contact'),
        ),
    ]
