# Generated by Django 3.2.15 on 2022-11-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20221119_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='template_sending_enabled',
            new_name='whatsapp_template_sending_enabled',
        ),
        migrations.AddField(
            model_name='site',
            name='active_campaign_leads_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
