# Generated by Django 3.2.15 on 2022-11-19 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20221119_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='whatsapp_business_account_id',
        ),
        migrations.AlterField(
            model_name='whatsappnumber',
            name='whatsapp_business_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.whatsappbusinessaccount'),
        ),
    ]
