# Generated by Django 3.2.15 on 2022-12-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20221130_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
