# Generated by Django 3.2.15 on 2022-12-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_company_whatsapp_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='active_campaign_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='calendly_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='campaign_leads_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='free_taster_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='whatsapp_enabled',
        ),
        migrations.AddField(
            model_name='company',
            name='subscription',
            field=models.CharField(default='lite', max_length=5),
        ),
    ]
