# Generated by Django 3.2.15 on 2022-12-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20221202_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription',
            field=models.CharField(choices=[('lite', 'Lite'), ('paid', 'Paid'), ('pro', 'Pro')], default='lite', max_length=5),
        ),
    ]
