# Generated by Django 3.2.15 on 2022-12-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_company_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('lite', 'Lite'), ('pro', 'Pro')], default='lite', max_length=5),
        ),
    ]
