# Generated by Django 3.2.15 on 2022-12-06 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_attachederror_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUsersOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users_online', models.CharField(default=';', max_length=1500)),
                ('feature', models.CharField(default='leads', max_length=50)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
            ],
        ),
    ]
