# Generated by Django 3.2.15 on 2022-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_siteusersonline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_app_business_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
