# Generated by Django 3.2.15 on 2022-12-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_company_whatsapp_app_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfilePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_site_configuration', models.BooleanField(default=False)),
                ('edit_site_configuration', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
    ]
