# Generated by Django 3.2.15 on 2022-12-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_siteprofilepermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofilepermissions',
            name='toggle_whatsapp_sending',
            field=models.BooleanField(default=False),
        ),
    ]
