# Generated by Django 3.2.15 on 2022-12-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_siteprofilepermissions_toggle_whatsapp_sending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofilepermissions',
            old_name='toggle_whatsapp_sending',
            new_name='toggle_whatsapp_template_sending',
        ),
    ]
