# Generated by Django 3.2.15 on 2022-12-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rename_toggle_whatsapp_sending_siteprofilepermissions_toggle_whatsapp_template_sending'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofilepermissions',
            name='toggle_toggle_active_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
