# Generated by Django 3.2.15 on 2022-12-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_siteprofilepermissions_toggle_toggle_active_campaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofilepermissions',
            old_name='toggle_whatsapp_template_sending',
            new_name='edit_whatsapp_settings_sending',
        ),
    ]
