# Generated by Django 3.2.15 on 2022-12-08 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_rename_toggle_whatsapp_template_sending_siteprofilepermissions_edit_whatsapp_settings_sending'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofilepermissions',
            old_name='edit_whatsapp_settings_sending',
            new_name='edit_whatsapp_settings',
        ),
    ]
