# Generated by Django 3.2.15 on 2022-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_edit_whatsapp_settings_sending_siteprofilepermissions_edit_whatsapp_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofilepermissions',
            name='edit_user_permissions',
            field=models.BooleanField(default=False),
        ),
    ]
