# Generated by Django 3.2.15 on 2022-12-11 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0018_auto_20221206_0314'),
        ('core', '0045_auto_20221208_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campaign_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_leads.campaigncategory'),
        ),
    ]
