# Generated by Django 3.2.15 on 2022-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20221213_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme_colour',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
