# Generated by Django 3.2.15 on 2022-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_profile_theme_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=5),
        ),
    ]
