# Generated by Django 3.2.15 on 2022-12-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_company_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
