# Generated by Django 3.2.15 on 2022-12-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_company_demo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='theme_colour',
            new_name='demo_account_theme_colour',
        ),
    ]
