# Generated by Django 3.2.15 on 2022-12-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_attachederror_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='demo_account_theme_colour',
            field=models.CharField(blank=True, default='', max_length=16, null=True),
        ),
    ]
