# Generated by Django 3.2.15 on 2022-12-17 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created']},
        ),
    ]
