# Generated by Django 3.2.15 on 2022-12-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_feedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
