# Generated by Django 3.2.15 on 2022-12-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_site_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='subscription',
        ),
        migrations.AddField(
            model_name='site',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro')], default='free', max_length=5),
        ),
    ]
