# Generated by Django 3.2.15 on 2022-12-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20221220_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesubscriptionchange',
            name='bootstrap_colour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
