# Generated by Django 3.2.15 on 2022-12-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20221220_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesubscriptionchange',
            name='bootstrap_colour',
        ),
        migrations.AddField(
            model_name='subscription',
            name='bootstrap_colour',
            field=models.TextField(blank=True, null=True),
        ),
    ]
