# Generated by Django 3.2.15 on 2022-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20221220_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='analytics_string',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='max_of_this_type',
            field=models.IntegerField(default=0),
        ),
    ]
