# Generated by Django 3.2.15 on 2022-12-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20221220_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='analytics_numerical',
            field=models.IntegerField(default=0),
        ),
    ]
