# Generated by Django 3.2.15 on 2022-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_subscription_analytics_numerical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='analytics_numerical',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='numerical',
            field=models.FloatField(default=0),
        ),
    ]
