# Generated by Django 3.2.15 on 2022-12-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20221220_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='max_users',
            new_name='max_profiles',
        ),
        migrations.AddField(
            model_name='subscription',
            name='visible_to_all',
            field=models.BooleanField(default=True),
        ),
    ]
