# Generated by Django 3.2.15 on 2022-12-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20221220_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='max_profiles_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
