# Generated by Django 3.2.15 on 2022-12-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_subscription_max_profiles_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofilepermissions',
            name='change_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
