# Generated by Django 3.2.15 on 2022-12-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_siteprofilepermissions_edit_site_calendly_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesubscriptionchange',
            name='version_started',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesubscriptionchange',
            name='canceled',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sitesubscriptionchange',
            name='completed',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sitesubscriptionchange',
            name='subscription_from_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesubscriptionchange',
            name='subscription_to_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
