# Generated by Django 3.2.15 on 2022-12-22 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20221222_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscription_link',
            new_name='stripe_subscription_link',
        ),
    ]
