# Generated by Django 3.2.15 on 2022-12-23 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_stripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesubscriptionchange',
            name='stripe_session_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
