# Generated by Django 3.2.15 on 2022-12-23 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_sitesubscriptionchange_stripe_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='stripe_subscription_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=[], null=True, size=None),
        ),
    ]
