# Generated by Django 3.2.15 on 2022-12-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_site_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoverride',
            name='site',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site'),
        ),
        migrations.AlterField(
            model_name='subscriptionoverride',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subscription'),
        ),
        migrations.DeleteModel(
            name='StripeSubscriptionSnapshot',
        ),
    ]
