# Generated by Django 3.2.15 on 2022-12-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_sitesubscriptionchange_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='billing_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
