# Generated by Django 3.2.15 on 2022-12-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_sitesubscriptionchange_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_secret', models.TextField()),
            ],
        ),
    ]
