# Generated by Django 3.2.15 on 2022-12-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_stripeconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconfig',
            name='webhook_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stripeconfig',
            name='webhook_secret',
            field=models.TextField(blank=True, null=True),
        ),
    ]
