# Generated by Django 3.2.15 on 2023-01-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_attachederror_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='register_uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
