# Generated by Django 3.2.15 on 2023-01-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_company_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='subscription_new',
            new_name='subscription',
        ),
        migrations.RemoveField(
            model_name='site',
            name='subscription_old',
        ),
    ]
