# Generated by Django 3.2.15 on 2023-01-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_auto_20230122_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sign_up_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sign_up_subscription_site', to='core.subscription'),
        ),
    ]
