# Generated by Django 3.2.15 on 2023-01-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_site_sign_up_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
