# Generated by Django 3.2.15 on 2023-02-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_site_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='billing_email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
