# Generated by Django 3.2.15 on 2023-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20230210_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofilepermissions',
            name='edit_whatsapp_settings',
        ),
        migrations.AddField(
            model_name='companyprofilepermissions',
            name='edit_whatsapp_settings',
            field=models.BooleanField(default=False),
        ),
    ]
