# Generated by Django 3.2.15 on 2023-02-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_auto_20230215_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
