# Generated by Django 3.2.15 on 2023-02-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_company_whatsapp_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='whatsapp_access_token',
            new_name='whatsapp_access_token_old',
        ),
    ]
