# Generated by Django 3.2.15 on 2023-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_rename_whatsapp_access_token_site_whatsapp_access_token_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappbusinessaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
