# Generated by Django 3.2.15 on 2023-02-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_attachederror_site_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecontact',
            old_name='first_name_old',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='sitecontact',
            old_name='last_name_old',
            new_name='last_name',
        ),
    ]
