# Generated by Django 3.2.15 on 2023-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20230217_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer_number',
            field=models.CharField(default='test default 2', max_length=50),
            preserve_default=False,
        ),
    ]
