# Generated by Django 3.2.15 on 2023-03-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_contact_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofilepermissions',
            name='edit_active_campaign_settings',
            field=models.BooleanField(default=False),
        ),
    ]
