# Generated by Django 3.2.15 on 2022-10-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0005_auto_20221023_0957'),
        ('calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendlywebhookrequest',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_leads.booking'),
        ),
    ]
