# Generated by Django 3.2.15 on 2022-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendly', '0002_alter_calendlywebhookrequest_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlywebhookrequest',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
