# Generated by Django 3.2.15 on 2022-10-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_messageimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='secure/message_image_thumnails/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='messageimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='secure/message_images/% Y/% m/% d/'),
        ),
    ]
