# Generated by Django 3.2.15 on 2022-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_alter_messageimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='failed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
