# Generated by Django 3.2.15 on 2023-02-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_attachederror_site_contact'),
        ('messaging', '0011_message_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='site_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sitecontact'),
        ),
    ]
