# Generated by Django 3.2.15 on 2022-10-14 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221014_1902'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhatsAppWebhook',
            new_name='WhatsAppWebhookRequest',
        ),
    ]
