# Generated by Django 3.2.15 on 2022-10-17 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221017_1151'),
        ('whatsapp', '0002_rename_whatsappwebhook_whatsappwebhookrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapptemplate',
            name='send_order',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='whatsappnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.whatsappnumber'),
        ),
    ]
