# Generated by Django 3.2.15 on 2022-10-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_auto_20221017_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapptemplate',
            name='latest_reason',
        ),
    ]
