# Generated by Django 3.2.15 on 2022-10-28 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messageimage'),
        ('whatsapp', '0006_alter_whatsappmessagestatus_whatsapp_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappMessageImage',
            fields=[
                ('messageimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messaging.messageimage')),
                ('media_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('messaging.messageimage',),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='image',
            field=models.ManyToManyField(to='whatsapp.WhatsappMessageImage'),
        ),
    ]
