# Generated by Django 3.2.15 on 2022-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0008_whatsappmessage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappmessage',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='whatsapp.WhatsappMessageImage'),
        ),
    ]
