# Generated by Django 3.2.15 on 2022-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0009_alter_whatsappmessage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappwebhookrequest',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
