# Generated by Django 3.2.15 on 2022-11-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0010_whatsappwebhookrequest_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='send_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
