# Generated by Django 3.2.15 on 2022-11-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_whatsappmessage_send_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='latest_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
