# Generated by Django 3.2.15 on 2022-11-19 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20221119_2337'),
        ('whatsapp', '0012_whatsapptemplate_latest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsapptemplate',
            name='site',
        ),
        migrations.AddField(
            model_name='whatsapptemplate',
            name='whatsapp_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.whatsappbusinessaccount'),
        ),
    ]
