# Generated by Django 3.2.15 on 2022-10-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendly_event_uri',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
