# Generated by Django 3.2.15 on 2022-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0003_auto_20221017_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='last_dragged',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
