# Generated by Django 3.2.15 on 2022-11-20 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_site_default_number'),
        ('campaign_leads', '0006_auto_20221028_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.whatsappbusinessaccount'),
        ),
    ]
