# Generated by Django 3.2.15 on 2022-11-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0007_campaign_whatsapp_business_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='color',
            field=models.CharField(default='96,248,61', max_length=15),
        ),
    ]
