# Generated by Django 3.2.15 on 2022-11-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaign_leads', '0008_campaign_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='marked_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaignlead_sold_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
