# Generated by Django 3.2.15 on 2022-11-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0009_auto_20221126_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlead',
            old_name='complete',
            new_name='archived',
        ),
    ]
