# Generated by Django 3.2.15 on 2022-12-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_auto_20221119_2337'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('campaign_leads', '0014_auto_20221204_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='fifth_send_template',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='first_send_template',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='fourth_send_template',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='second_send_template',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='third_send_template',
        ),
        migrations.CreateModel(
            name='CampaignTemplateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_order', models.IntegerField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaign_leads.campaign')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_campaign_leads.campaigntemplatelink_set+', to='contenttypes.contenttype')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='whatsapp.whatsapptemplate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
