# Generated by Django 3.2.15 on 2022-12-04 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_auto_20221119_2337'),
        ('campaign_leads', '0015_auto_20221204_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntemplatelink',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_leads.campaign'),
        ),
        migrations.AlterField(
            model_name='campaigntemplatelink',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whatsapp.whatsapptemplate'),
        ),
    ]
