# Generated by Django 3.2.15 on 2022-12-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0018_auto_20221206_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
    ]
