# Generated by Django 3.2.15 on 2023-01-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0019_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignlead',
            name='email',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='campaignlead',
            name='first_name',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='campaignlead',
            name='last_name',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
