# Generated by Django 3.2.15 on 2023-01-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0021_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlead',
            old_name='marked_sold',
            new_name='marked_sold_old',
        ),
        migrations.RenameField(
            model_name='campaignlead',
            old_name='sold_by',
            new_name='sold_by_old',
        ),
        migrations.RenameField(
            model_name='campaignlead',
            old_name='sold',
            new_name='sold_old',
        ),
    ]
