# Generated by Django 3.2.15 on 2023-01-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0023_alter_campaignlead_sold_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='disabled_automated_messaging',
            field=models.BooleanField(default=False),
        ),
    ]
