# Generated by Django 3.2.15 on 2023-02-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0024_campaignlead_disabled_automated_messaging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='error_json',
        ),
        migrations.AlterField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campaign_leads.campaignlead'),
        ),
    ]
