# Generated by Django 3.2.15 on 2023-02-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_whatsappbusinessaccount_active'),
        ('campaign_leads', '0025_auto_20230207_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaignlead',
            old_name='whatsapp_number',
            new_name='whatsapp_number_old',
        ),
        migrations.RemoveField(
            model_name='campaignlead',
            name='marked_sold_old',
        ),
        migrations.RemoveField(
            model_name='campaignlead',
            name='sold_by_old',
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.contact'),
        ),
    ]
