# Generated by Django 3.2.15 on 2023-02-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_auto_20230217_1453'),
        ('campaign_leads', '0026_auto_20230217_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='site_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sitecontact'),
        ),
    ]
