# Generated by Django 3.2.15 on 2023-03-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0027_campaignlead_site_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='active_sale',
            field=models.BooleanField(default=False),
        ),
    ]
