# Generated by Django 3.2.15 on 2023-03-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0029_booking_lead_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='campaign_leads.campaignlead'),
        ),
    ]
