# Generated by Django 3.2.15 on 2023-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0030_alter_booking_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntemplatelink',
            name='call_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntemplatelink',
            name='method',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='campaigntemplatelink',
            name='time_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
