# Generated by Django 3.2.15 on 2022-10-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_leads', '0002_auto_20221014_1902'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('whatsapp', '0002_rename_whatsappwebhook_whatsappwebhookrequest'),
        ('core', '0002_auto_20221014_1902'),
        ('active_campaign', '0002_rename_activecampaignwebhook_activecampaignwebhookrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveCampaignList',
            new_name='ActiveCampaign',
        ),
    ]
