# Generated by Django 3.2.15 on 2022-11-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active_campaign', '0003_rename_activecampaignlist_activecampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='activecampaignwebhookrequest',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
    ]
